version: '3'

services:
  web:
    environment:
      API_URL: ${API_URL}
      CMS_URL: ${CMS_URL}
      OP_DOMAIN: ${OP_DOMAIN}
      OP_ISSUER: ${OP_ISSUER}
      OP_ID: ${OP_ID}
      OP_SECRET: ${OP_SECRET}
      REFRESH_PERIOD: ${REFRESH_PERIOD}
      LOGOUT_IF_IDLE_PERIOD: ${LOGOUT_IF_IDLE_PERIOD}
      REQUIRE_HTTPS: ${REQUIRE_HTTPS}
      LOCAL: ${LOCAL}
      SECRET_KEY: ${SECRET_KEY}
      STAGE: ${STAGE}
    build: ./cms
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./cms:/code
    ports:
      - "12000:8000"
