version: '3'

services:
  web:
    environment:
      API_URL: ${API_URL}
    build: ./cms
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./cms:/code
    ports:
      - "12000:8000"
    
  api:
    build: ./mock_api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mock_api:/code
    ports:
      - "9000:8000"
